name: Test Autonity

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      ### INSTALL DEPENDENCIES ###
      - name: Install Kubectl
        uses: Azure/setup-kubectl@v1
        with:
          # Version of kubectl
          version: v1.18.4
        
      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          # Version of helm
          version: v3.2.4
          token: ${{ github.token }}
        
      - name: Install Kind & Create cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          name: autonity-network
          wait: 60s
          skipClusterCreation: false
            
      - name: Save config
        uses: actions/upload-artifact@v2
        with:
          name: kind-config-file
          path: ./.kube/config
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
      - name: Download config file
        uses: actions/download-artifact@v2
        with:
          name: kind-config-file
      
      
      ### TEST INSTALLATIONS ###
      - name: Test Helm install
        run: helm version
        
      - name: Test Kind install
        run: kind version
        
      - name: Test Kind cluster creation
        run: kind get clusters
        
      - name: Test Kuberctl install
        run: kubectl version
      
      ### CREATE AUTONITY ###
      - name: Initialise Helm repositories
        run: |
          helm repo add charts-ose.clearmatics.com https://charts-ose.clearmatics.com/
          helm repo update
      
      - name: Create Autonity namespace
        run: kubectl create namespace autonity-network
        
      - name: Install Helm chart
        run: helm install autonity-network charts-ose.clearmatics.com/autonity-network --namespace autonity-network --version 1.8.0
        
      - name: Check Autonity is running
        run: |
          sleep 30s
          kubectl get pods --namespace autonity-network
